[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
  command = "npm run build"  # Asegúrate de que el comando de construcción sea el adecuado para tu proyecto
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
  from = "/admin/alumnos-detalles/:curp"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/resultados/:curp"
  to = "/index.html"
  status = 200
